language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'

services:
  - mysql

addons:
  - mariadb: '10.2'
  - mariadb: '10.3'

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS phparcade;'
  - mysql -u root phparcade < installation/create_database.sql

install:
  - composer install --no-dev

script: phpunit tests

